---
 - name: install web server packages
   tags: apache,apache2,centos,httpd,ubuntu
   package:
     name:
       - "Template:Apache package name"
       - "Template:Php package name"
     state: latest
   when: ansible_distribution == "CentOS"
 
 - name: start and enable apache
   tags: apache,centos,httpd
   service:
     name: "Template:Apache service"
     state: started
     enabled: yes
 